<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\Entity\User;

/**
* @file
* Module for CSSN.
*/

/**
 * Implements hook_form_alter().
 */
function cssn_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'webform_submission_join_the_cssn_network_add_form') {
    $form['actions']['submit']['#submit'][] = 'cssn_form_submit';
  }
}

/**
 * Implements hook_form_submit().
 */
function cssn_form_submit(&$form, FormStateInterface $form_state) {
  $elements = $form['elements']['i_am_joining_as_a_'];
  $general = $elements['General Member']['#checked'];
  $match_mentor = $elements['MATCHPlus Mentor']['#checked'];
  $student_facilitator = $elements['Student-Facilitator']['#checked'];
  $premier_consultant = $elements['Premier Consultant']['#checked'];
  // Lookup taxonomy term id by name 'ACCESS CSSN'.
  $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadByProperties(['name' => 'ACCESS CSSN']);
  $term = reset($term);
  $term_id = $term->id();
  cssn_role_region('cssn', $general, $term_id);
  cssn_role_region('mentor', $match_mentor, $term_id);
  cssn_role_region('student', $student_facilitator, $term_id);
}


/**
 * Set or remove role and region.
 */
function cssn_role_region($role, $checked, $term_id) {
  if ($checked) {
    cssn_add_role($role);
    if ($role == 'cssn') {
      cssn_add_field_region($term_id);
    }
  } else {
    cssn_remove_role($role);
    if ($role == 'cssn') {
      cssn_remove_field_region($term_id);
    }
  }
}

/**
 * Add role to user.
 */
function cssn_add_role($role) {
  $user = \Drupal::currentUser();
  $account = User::load($user->id());
  if (!$account->hasRole($role)) {
    \Drupal::messenger()->addMessage(t('The following role added: @role', ['@role' => $role]));
  }
  $account->addRole($role);
  $account->save();
}

/**
 * Remove role from user.
 */
function cssn_remove_role($role) {
  $user = \Drupal::currentUser();
  $account = User::load($user->id());
  if ($account->hasRole($role)) {
    \Drupal::messenger()->addMessage(t('The following role removed: @role', ['@role' => $role]));
  }
  $account->removeRole($role);
  $account->save();
}

/**
 * Add item to field_region.
 */
function cssn_add_field_region($region) {
  $user = \Drupal::currentUser();
  $account = User::load($user->id());
  $values = $account->field_region->getValue();
  foreach ($values as $key => $value) {
    if (!$value['target_id'] == $region) {
      unset($values[$key]);
      \Drupal::messenger()->addMessage(t('You have been added to the CSSN Program.'));
    }
  }
  $account->field_region->appendItem($region);
  $account->save();
}

/**
 * Remove item to field_region.
 */
function cssn_remove_field_region($region) {
  $user = \Drupal::currentUser();
  $account = User::load($user->id());
  $values = $account->field_region->getValue();
  foreach ($values as $key => $value) {
    if ($value['target_id'] == $region) {
      unset($values[$key]);
      \Drupal::messenger()->addMessage(t('You have been removed from the CSSN Program.'));
    }
  }
  $account->field_region->setValue($values);
  $account->save();
}
