<?php

/**
 * @file
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Menu\MenuTreeParameters;

/**
 * Implements hook_page_attachments().
 */
function access_page_attachments(array &$attachments) {
  $token = \Drupal::token();
  $domain_name = Html::getClass($token->replace(t('[domain:name]')));

  if ($domain_name = "access-support") {

    // Get 'access-secondary-menu' menu items and links.
    $tree = \Drupal::menuTree()->load('access-secondary-menu', new MenuTreeParameters());
    $menu = [];
    foreach ($tree as $item) {
      $title = $item->link->getTitle();
      // Get weight.
      $weight = $item->link->getWeight();
      // Counteract negative weights.
      $weight = $weight + 200;
      $menu[$weight]['name'] = $title;
      foreach ($item->subtree as $subitem) {
        $sub_weight = $subitem->link->getWeight() + 200;
        $sub_title = $subitem->link->getTitle();
        $sub_url_obj = $subitem->link->getUrlObject();
        $sub_url = $sub_url_obj->toString();
        $menu[$weight]['items'][$sub_weight]['name'] = $sub_title;
        $menu[$weight]['items'][$sub_weight]['url'] = $sub_url;
      }
    }
    ksort($menu);

    $js_menu = '[';
    foreach ($menu as $menu_items) {
      $js_menu .= '{';
      $js_menu .= '"name": "' . $menu_items['name'] . '", "items": [';
      ksort($menu_items['items']);
      foreach ($menu_items['items'] as $item) {
        $js_menu .= '{"name": "' . $item['name'] . '", "href": "' . $item['url'] . '"},';
      }
      // remove last comma
      $js_menu = rtrim($js_menu, ',');
      $js_menu .= ']},';
    }
    // remove last comma
    $js_menu = rtrim($js_menu, ',');
    $js_menu .= ']';

    // Adding global library to all pages.
    $attachments['#attached']['drupalSettings']['access']['current_menu'] = $js_menu;
    $attachments['#attached']['library'][] = 'access/header_footer_library';
  }
}
