<?php

/**
 * @file
 * Module for customizing match_engagement node.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function access_match_engagement_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $current_user = \Drupal::currentUser();
  $roles = $current_user->getRoles();
  $accepted = $form_state->getValue(['field_accepted']);
  $form['field_requested_engagement']['#access'] = FALSE;
  $form['field_project_image']['#access'] = FALSE;
  $form['field_project_deliverables']['#access'] = FALSE;
  $form['field_mileston']['#access'] = FALSE;
  $form['field_field_group']['#access'] = FALSE;
  $form['field_milestone_completion_date']['#access'] = FALSE;
  $form['field_milestone_actual_date']['#access'] = FALSE;
  $form['field_hpc_resources_needed']['#access'] = FALSE;
  $form['field_mentor']['#access'] = FALSE;
  $form['field_students']['#access'] = FALSE;
  $form['field_qualifications']['#access'] = FALSE;
  $form['field_student_learning']['#access'] = FALSE;
  $form['field_education']['#access'] = FALSE;
  $form['field_programming_skill_level']['#access'] = FALSE;
  $form['field_launch_presentation']['#access'] = FALSE;
  $form['field_launch_presentation_date']['#access'] = FALSE;
  $form['field_wrap_presentation']['#access'] = FALSE;
  $form['field_wrap_presentation_date']['#access'] = FALSE;
  $form['field_git_contribution']['#access'] = FALSE;
  $form['field_planned_portal_contributio']['#access'] = FALSE;
  $form['field_planned_publications']['#access'] = FALSE;
  $form['field_what_match_will_learn']['#access'] = FALSE;
  $form['field_notes']['#access'] = FALSE;
  $form['field_what_is_the_impact_on_othe']['#access'] = FALSE;
  $form['What is the impact on the development discipline(s) of the project?']['#access'] = FALSE;
  $form['field_is_there_an_impact_on_info']['#access'] = FALSE;
  $form['field_is_there_an_impact_on_inst']['#access'] = FALSE;
  $form['field_is_there_an_impact_on_soci']['#access'] = FALSE;
  $form['field_is_there_an_impact_on_tech']['#access'] = FALSE;
  $form['field_is_there_an_impact_physica']['#access'] = FALSE;
  $form['field_lessons_learned']['#access'] = FALSE;
  $form['field_overall_results']['#access'] = FALSE;
  $form['field_status']['#access'] = FALSE;
  if (!in_array('administrator', $roles)) {
    $form['field_accepted']['#access'] = FALSE;
  }
}