<?php

/**
 * @file
 * Module updates.
 */

use Drupal\taxonomy\Entity\Term;

/**
 *
 */
function access_mentorship_engagement_install() {
  // Add the tag 'Recruiting' to the 'State' Taxonomy.
  $states = [
    'Recruiting',
    'Review Applicants',
    'In Progress',
    'On Hold',
    'Finishing Up',
    'Complete',
    'Halted',
  ];

  $weight = 0;

  foreach ($states as $state) {
    $term = Term::create([
      'name' => $state,
      'vid' => 'state',
      'weight' => $weight,
    ]);
    $term->save();
    $weight++;
  }
}

/**
 * Ajax callback function to replace the section with '#markup'.
 */
function access_match_engagement_replace_section_callback(array &$form, FormStateInterface $form_state) {
  $raw_data = $form_state->getUserInput();
  $body_filter = Xss::filter($raw_data['body'][0]['value']);
  $suggested_tag_ids = '0';
  if (strlen($body_filter) >= 400) {
    $llm = \Drupal::service('access_llm.ai_references_generator');
    $llm->generateTaxonomyPrompt('tags', 1, $body_filter);
    $suggested_tag_ids = implode(', ', $llm->taxonomyIdSuggested());
    $form['field_tags_replace']['user_message'] = [
      '#markup' => "",
    ];
  }
  else {
    $form['field_tags_replace']['user_message'] = [
      '#markup' => "<div class='match-tag-list bg-blue-200 text-sky-900 my-5 p-5'>
                    <strong class='text-sky-900'>Fill in the description above to get suggested tags.</strong><br />
                    Your description must be over 400 characters to get a suggestion.</div>",
    ];
  }
  $form['field_tags_replace']['#attributes']['data-suggest'] = $suggested_tag_ids ;

  // Return the updated section.
  return $form['field_tags_replace'];
}
