<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function access_outages_theme() {
  return [
    'outages_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

/**
 * Help display affinity group outages by passing cider resource ids to
 * to the access_outages library
 */
function access_outages_preprocess_layout(&$vars) {
  $entity = $vars['content']['#entity'];
  if ($entity->bundle() == 'affinity_group') {
    $node_storage = \Drupal::entityTypeManager()->getStorage('node');
    $cider_resource_ids = [];
    if ($entity->hasField('field_cider_resources')) {
      $cider_ids = $entity->get('field_cider_resources')->getValue();
      foreach ($cider_ids as $cider_id) {
        $node = $node_storage->load($cider_id['target_id']);
        $cider_resource_ids[] = $node->get('field_access_global_resource_id')->value;
      }
    }
    if (count($cider_resource_ids) > 0) {
      $vars['#attached']['library'][] = 'access_outages/outages_library';
      $vars['#attached']['drupalSettings'] = ['ciderIds' => $cider_resource_ids];
    }
  }
}
