<?php

/**
 * Implements hook_theme().
 */
function access_outages_theme()
{
  return [
    'outages_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

function access_outages_preprocess_views_view(&$vars)
{

  // kint('$vars[\'view\']->id() = ' . $vars['view']->id());

  // other ways of looking for getting view name don't work in current drupal
  // if ($view->name == 'affinity_group' && $view->current_display === 'group') {

  if (isset($vars['view']) && $vars['view']->id() == 'affinity_group') {

    $view = &$vars['view'];
    kint('class of vars = ' . get_class($vars));
    kint('class of view = ' . get_class($view));

    // need to get the resource ids associated with the ag, set those into 
    // the vars for the view that will be accessed from js

    // can't kint $vars -- breaks website
    // kint(print_r($vars, true));

    $vars['#attached']['library'][] = 'access_outages/access_outages.libraries.yml';

    $vars['#attached']['drupalSettings'] = [
      'agData' => [
        'agResourceId' => 1,
      ],
    ];

    kint('$vars[\'#attached\'] = ' . print_r($vars['#attached'], true));
  }
}
