<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_theme().
 */
function access_outages_theme()
{
  return [
    'outages_block' => [
      'variables' => [
        'data' => [],
      ],
    ],
  ];
}

/**
 * Help display affinity group outages by passing cider resource ids to
 * to the access_outages library
 */
function access_outages_preprocess_views_view(&$vars)
{
  $view = &$vars['view'];
  if ($view->id() == 'affinity_group' &&  $view->current_display == 'group') {

    $node_storage = \Drupal::entityTypeManager()->getStorage('node');

    $cider_resource_ids = [];
    $cider_resource_titles = [];
    $cider_resource_descriptions = [];

    foreach ($view->result as $key => $value) {
      if ($value->_entity->hasField('field_cider_resources')) {
        $cider_ids = $value->_entity->get('field_cider_resources')->getValue();

        foreach ($cider_ids as $cider_id) {
          $node = $node_storage->load($cider_id['target_id']);
          $cider_resource_ids[] = $node->get('field_access_global_resource_id')->value;
          $cider_resource_titles[] = $node->get('title')->value;
          $cider_resource_descriptions[] = $node->get('body')->value;
          
          // \Drupal::messenger()->addStatus(basename(__FILE__) . ':' . __LINE__ . ' -- ' . print_r($node->toArray(),true));
          // \Drupal::messenger()->addStatus(basename(__FILE__) . ':' . __LINE__ . ' -- ' . print_r($node->get('body')->value,true));

        }

        // $msg = "cider_resource_descriptions= " . print_r($cider_resource_descriptions, true);
        // \Drupal::messenger()->addStatus(basename(__FILE__) . ':' . __LINE__ . ' -- ' . $msg);
      }
    }

    if (count($cider_resource_ids) > 0) {
      $vars['#attached']['library'][] = 'access_outages/outages_library';
      $vars['#attached']['drupalSettings'] = [
        'ciderIds' => $cider_resource_ids, 
        'ciderTitles' => $cider_resource_titles, 
        'ciderDescriptions' => $cider_resource_descriptions,
      ];
    }
  }
}
