<?php

/**
 * @file
 */

use Drupal\Core\Render\Markup;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Drupal\user\Entity\User;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_pre_render().
 */
function access_cilink_views_pre_render(ViewExecutable $view) {
  if ($view->id() == 'resource' && isset($view->getDisplay()->view->element['#display_id']) && $view->getDisplay()->view->element['#display_id'] == 'page_1') {
    $view->element['#attached']['library'][] = 'access_cilink/resource_view';
  }
}

/**
 * Implements hook_views_post_render().
 */
function access_cilink_views_post_render(ViewExecutable $view) {
  // Override view /admin/structure/views/view/resources/edit/page_2 title.
  if ($view->id() == 'resources' && isset($view->getDisplay()->view->element['#display_id']) && $view->getDisplay()->view->element['#display_id'] == 'page_2') {
    $tid = $view->getTitle();
    if (term::load($tid)) {
      $title = 'CI Links tagged ' . term::load($tid)->get('name')->value;
      // Set the view title.
      $view->setTitle($title);
      // Set the route title.
      $route = \Drupal::routeMatch()->getCurrentRouteMatch()->getRouteObject();
      $route->setDefault('_title', $title);
    }
  }
  if ($view->id() == 'resource' && isset($view->getDisplay()->view->element['#display_id']) && $view->getDisplay()->view->element['#display_id'] == 'page_1') {
    $url = \Drupal::request()->getRequestUri();
    $url_chunked = explode('/', $url);
    $title = 'Ci Link';
    if (is_numeric($url_chunked[2])) {
      $sid = $url_chunked[2];
      $webform_submission = \Drupal::entityTypeManager()->getStorage('webform_submission')->load($sid);
      // Get title field from webform submission.
      $webform_title = $webform_submission->getData('title');
      $title = $webform_title['title'];
    }
    $view->setTitle($title);
  }
}

/**
 * Implements hook_preprocess_views_view_field().
 */
function access_cilink_preprocess_views_view_field(&$variables) {
  $view = $variables['view'];

  $field = $variables['field'];
  // Override view /admin/structure/views/view/search_ci_links title.
  // Links on CI links search on /search-ci-links page.
  if ($view->id() == 'search_ci_links' && ($view->current_display == 'page_1' && $field->options['id'] == 'webform_submission_description')) {
    if ($variables['output']) {
      $description = $variables['output']->__toString();
      // Grab the first number from the description.
      preg_match_all('!^\d+!', $description, $matches);
      $sid = $matches[0][0];
      // Rewrite description to remove the sid.
      $description = preg_replace('!^\d+!', '', $description);
      // Lookup webform submission by sid.
      $webform_submission = \Drupal::entityTypeManager()->getStorage('webform_submission')->load($sid);
      if (!$webform_submission) {
        return;
      }
      // Get link_to_resource field from webform submission.
      $data = $webform_submission->getData();
      $link_to_resource = '<ul class="list-none m-0 p-0">';
      foreach ($data['link_to_resource'] as $link) {
        $link_to_resource .= "<li class='list-image-link'><a href='" .
          $link['url'] .
          "' class='text-dark-teal text-lg no-underline hover--underline font-semibold'>" .
          $link['title'] . "</a></li>";
      }
      $link_to_resource .= '</ul>';
      $description_html = "<div class='px-5'>$link_to_resource $description</div>";
      $variables['output'] = Markup::create($description_html);
    }
  }
  // Upvote widget on CI links search on /search-ci-links page.
  if ($view->id() == 'search_ci_links' && ($view->current_display == 'page_1' && $field->options['id'] == 'sid_1')) {
    $sid = $variables['output']->__toString();
    $webform_submission = \Drupal::entityTypeManager()->getStorage('webform_submission')->load($sid);
    // Upvote widget.
    $flag_upvote = \Drupal::service('flag.link_builder')->build('webform_submission', $sid, 'upvote');
    $flag_upvote = \Drupal::service('renderer')->renderPlain($flag_upvote);
    $flag_upvote = "<div class='[&_a]--block text-center'>$flag_upvote</div>";
    $flag_upvote_count = \Drupal::service('flag.count')->getEntityFlagCounts($webform_submission);
    $flag_upvote_set = $flag_upvote_count['upvote'] ?? 0;
    $flag_upvote_count = $flag_upvote_set ? $flag_upvote_count['upvote'] : 0;

    $likes_count = "<div class='text-[32px] text-dark-teal text-center'>$flag_upvote_count</div>";
    $likes = $flag_upvote_count == 1 ? "<span>Like</span>" : "<span>Likes</span>";
    // If User is not logged in, show the login link.
    if (\Drupal::currentUser()->isAnonymous()) {
      $flag_upvote = "<div class='text-center'>
                        <i class='fa-light fa-right-to-bracket text-[32px] w-9 me-2'></i>
                        <br><a href='user'>Login to like</a>
                      </div>";
    }
    $likes_html = "<div class='mb-5 text-center'>$likes_count $likes</div>";

    $output_html = "<div class='py-4'>$likes_html $flag_upvote</div>";

    $variables['output'] = Markup::create($output_html);
  }
  // Skill Level on CI links search on /search-ci-links page.
  if ($view->id() == 'search_ci_links' && ($view->current_display == 'page_1' && $field->options['id'] == 'nothing')) {
    if ($variables['output']) {
      $output = $variables['output']->__toString();
      $output = json_decode($output);
      $skill_list = explode(', ', $output->skill);
      $skill_image = \Drupal::service('access_misc.skillLevel')->getSkillsImage($skill_list);

      // Flags.
      $flag_classes = 'no-underline text-dark-teal hover--underline';
      $flag_outdated = \Drupal::service('flag.link_builder')->build('webform_submission', $output->sid, 'outdated');
      $flag_outdated['#attributes']['class'][] = $flag_classes;
      $flag_outdated = \Drupal::service('renderer')->renderPlain($flag_outdated);
      $flag_not_useful = \Drupal::service('flag.link_builder')->build('webform_submission', $output->sid, 'not_useful');
      $flag_not_useful['#attributes']['class'][] = $flag_classes;
      $flag_not_useful = \Drupal::service('renderer')->renderPlain($flag_not_useful);
      $flag_inaccurate = \Drupal::service('flag.link_builder')->build('webform_submission', $output->sid, 'inaccurate');
      $flag_inaccurate['#attributes']['class'][] = $flag_classes;
      $flag_inaccurate = \Drupal::service('renderer')->renderPlain($flag_inaccurate);
      $report = t('Flag This');

      $flag_link = "<details class='relative w-40'>
                  <summary>$report</summary>
                  <ul class='dropdown-menu px-2'>
                    <li>$flag_outdated</li>
                    <li>$flag_not_useful</li>
                    <li>$flag_inaccurate</li>
                  </ul>
                </details>";
      $flag_html = "<div class='pt-4'>$skill_image $flag_link</div>";

      $variables['output'] = Markup::create($flag_html);
    }
  }
  // Override view /admin/structure/views/view/resources/edit/page_1 sid_2.
  // Shows up as affinity group on /ci-links page.
  if ($view->id() == 'resources' && ($view->current_display == 'page_1' || $view->current_display == 'page_3') && $field->options['id'] == 'sid_2') {
    $sid = $variables['output'];
    $query = \Drupal::entityQuery('node')
      ->condition('type', 'affinity_group')
      ->condition('field_resources_entity_reference', $sid)
      ->accessCheck(FALSE);
    $nids = $query->execute();
    $affinity_nodes = '';
    foreach ($nids as $nid) {
      // Get node title.
      $node = Node::load($nid);
      $title = $node->getTitle();
      $affinity_nodes .= '<a href="/node/' . $nid . '">' . $title . '</a>, ';
    }
    $affinity_nodes = rtrim($affinity_nodes, ', ');

    $variables['output'] = Markup::create($affinity_nodes);
  }
  // Override view /admin/structure/views/view/resource/edit/page_1 sid_2.
  // Shows up as affinity group on /ci-links/%sid page.
  if ($view->id() == 'resource' && ($view->current_display == 'page_1' || $view->current_display == 'page_3')) {
    if ($field->options['id'] == 'webform_submission_value') {
      $html = $variables['output'];

      // Regular expression pattern to match the "[[REPLACE]]:473" string.
      $pattern = '/\[\[REPLACEAFFINITY\]\]:(\d+)/';

      // Match and extract the number using preg_match for Affinity Groups.
      if (preg_match($pattern, $html, $matches)) {
        $sid = $matches[1];
        $query = \Drupal::entityQuery('node')
          ->condition('type', 'affinity_group')
          ->condition('field_resources_entity_reference', $sid)
          ->accessCheck(FALSE);
        $nids = $query->execute();
        $affinity_nodes = '';
        if ($nids) {
          $affinity_nodes = '<h4>Affinity Group</h4>';
        }
        foreach ($nids as $nid) {
          // Get node title.
          $node = Node::load($nid);
          $title = $node->getTitle();
          $affinity_nodes .= '<a href="/node/' . $nid . '">' . $title . '</a>, ';
        }
        $replaced_text = rtrim($affinity_nodes, ', ');

        $html = preg_replace($pattern, $replaced_text, $html);
      }

      // Regular expression pattern to match the "[[REPLACE]]:473" string.
      $pattern = '/\[\[REPLACE\]\]:(\d+)/';

      // Match and extract the number using preg_match for report flags.
      if (preg_match($pattern, $html, $matches)) {
        $sid = $matches[1];
        $flag_outdated = \Drupal::service('flag.link_builder')->build('webform_submission', $sid, 'outdated');
        $flag_outdated['#attributes']['class'][] = 'dropdown-item';
        $flag_outdated = \Drupal::service('renderer')->renderPlain($flag_outdated);
        $flag_not_useful = \Drupal::service('flag.link_builder')->build('webform_submission', $sid, 'not_useful');
        $flag_not_useful['#attributes']['class'][] = 'dropdown-item';
        $flag_not_useful = \Drupal::service('renderer')->renderPlain($flag_not_useful);
        $flag_inaccurate = \Drupal::service('flag.link_builder')->build('webform_submission', $sid, 'inaccurate');
        $flag_inaccurate['#attributes']['class'][] = 'dropdown-item';
        $flag_inaccurate = \Drupal::service('renderer')->renderPlain($flag_inaccurate);

        $replaced_text = "<li>$flag_outdated</li><li>$flag_not_useful</li><li>$flag_inaccurate</li>";

        // Replace the matched string with the variable value.
        $updatedHtml = preg_replace($pattern, $replaced_text, $html);
        $output = Markup::create($updatedHtml);
        $variables['output'] = $output;
      }
    }
  }
}

/**
 * Implements hook_mail().
 */
function access_cilink_mail($key, &$message, $params) {
  switch ($key) {
    case 'cilink_resources':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['body'];
      break;
  }
}

/**
 * Build Resource Email.
 */
function access_cilink_resource_email() {
  $header = [
    'resource' => 'Resource title',
    'flags' => 'Flags',
  ];
  $rows = [];
  $flag_resources = \Drupal::state()->get('resource_flags');
  foreach ($flag_resources as $sid => $flag_resource) {
    if ($flag_resource['today']) {
      $flag = '';
      if (isset($flag_resource['not_useful'])) {
        $flag .= t('not_useful') . " " . $flag_resource['not_useful'] . "<br>";
      }
      if (isset($flag_resource['outdated'])) {
        $flag .= t('outdated') . " " . $flag_resource['outdated'] . "<br>";
      }
      if (isset($flag_resource['inaccurate'])) {
        $flag .= t('inaccurate') . " " . $flag_resource['inaccurate'] . "<br>";
      }
      // Webform lookup by submission id $sid.
      $webform_submission = \Drupal::entityTypeManager()->getStorage('webform_submission')->load($sid);
      $webform_title = $webform_submission->getWebform()->label();
      // Link to webform submission.
      $webform_submission_link = \Drupal::service('link_generator')
        ->generate($webform_submission->label(), $webform_submission->toUrl());
      $rows[] = [
        'resource' => [
          'data' => [
            '#markup' => $webform_submission_link->getGeneratedLink(),
          ],
        ],
        'flags' => [
          'data' => [
            '#markup' => $flag,
          ],
        ],
      ];
      // Reset today to 0 after processing.
      $flag_resources[$sid]['today'] = 0;
      \Drupal::state()->set('resource_flags', $flag_resources);
    }
  }

  if (!empty($rows)) {
    $body = t('The following resources have been flagged as inaccurate, not useful, or outdated.');
    $html['ask-ci'] = [
      '#theme' => 'table',
      '#prefix' => "<p>$body</p>",
      '#header' => $header,
      '#rows' => $rows,
      '#attributes' => ['id' => 'ask-ci', 'class' => ['border-0']],
    ];
    $output = \Drupal::service('renderer')->renderPlain($html);

    // Lookup users by role.
    $uids = \Drupal::entityQuery('user')
      ->condition('status', 1)
      ->condition('roles', 'kb_pm')
      ->accessCheck(FALSE)
      ->execute();
    $to_email = '';
    foreach ($uids as $uid) {
      $user = User::load($uid);
      $to_email .= $user->getEmail() . ',';
    }
    // Remove the last comma.
    $to_email = rtrim($to_email, ',');

    $params = [];
    $params['to'] = $to_email;
    $params['body'] = $output;
    $params['subject'] = t('CI Links flagged');
    cilink_send('cilink_resources', $params);
  }
}

/**
 * Send email.
 */
function cilink_send($key, $params) {
  $to = $params['to'];
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = TRUE;
  $module = 'access_cilink';
  $mailManager = \Drupal::service('plugin.manager.mail');
  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  return $result;
}

/**
 * Implements hook_cron().
 */
function access_cilink_cron() {
  $run_email = FALSE;
  if ((date('G', time()) == 8) && (date('i', time()) < 15)) {
    $run_email = TRUE;
  }
  if ($run_email) {
    \Drupal::logger('access_cilinks')->notice('Running access_cilink email cron.');
    access_cilink_resource_email();
  }
}
